language: node_js
node_js:
  - 'node'
env:
  global:
    - EXTENSION_ID=failppjoidijbialknplliogdmabniaf
deploy:
  provider: script
  script: npm run build; npm run version-from-git-tag; npm run release
  on:
    branch: master
    tags: true
